FROM node:20.15.1-alpine3.20@sha256:09dbe0a53523c2482d85a037efc6b0e8e8bb16c6f1acf431fe36aa0ebc871c06
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1 NODE_ENV=production
RUN addgroup -S app && adduser -S app -G app
COPY apps/web/package.json ./package.json
RUN npm install --omit=dev
COPY apps/web ./
RUN npm run build
USER app
EXPOSE 3000
CMD ["npm", "run", "start"]
