FROM node:20.15.1-alpine3.20
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1 NODE_ENV=production
RUN addgroup -S app && adduser -S app -G app
COPY apps/web/package.json ./package.json
RUN npm install --omit=dev
COPY apps/web ./
RUN npm run build
USER app
EXPOSE 3000
CMD ["npm", "run", "start"]
